### PR TITLE
Fix mise build pipeline on Windows

### PR DESCRIPTION
**Pull request by AttilaMihaly**
## Summary

The mise/Bun build pipeline introduced in #850bb4471 fails on Windows due to POSIX-only assumptions in `.mise/tasks/_lib.ts` and a missing task dependency. This PR makes `mise run default` succeed on Windows without affecting macOS/Linux behaviour.

## Root causes

1. **Absolute-path detection assumed POSIX.** `del`, `concat`, and `copyGlob` checked `path.startsWith("/")` to decide whether a path was absolute. On Windows, absolute paths begin with a drive letter, so the check returned false and `ROOT_DIR` was prepended a second time, producing doubled paths like `D:\…\morphir-elm\D:\…\cli\web\insight.js`. This is what crashed `build:components` with ENOENT.

2. **Separator stripping in `copyGlob` was POSIX-only.** After `Bun.Glob.scan` returned absolute paths, the relative portion was extracted via `file.replace(cwd, "").replace(/^\//, "")` — which leaves a leading backslash on Windows.

3. **Missing task dependency.** `build:morphir-ts` depended on `build:cli` only, but its `morphir gen -t TypeScript` step shells out through `cli2/lib/morphir-typescript-gen.js`, which requires `cli2/Morphir.Elm.CLI.cjs` produced by `build:cli2`. The edge was implicit, and the mise scheduler happened to satisfy it on macOS; on Windows it didn't, causing `Cannot find module './../Morphir.Elm.CLI.cjs'`. This was a latent race, not strictly a Windows bug.

## Changes

- `.mise/tasks/_lib.ts` — use `path.isAbsolute()` in `del`, `concat`, and `copyGlob`; use `path.relative()` in `copyGlob` instead of the hand-rolled prefix strip.
- `.mise/tasks/build/morphir-ts.ts` — add `build:cli2` to the `depends` list.

## Test plan

- [x] `mise run build` succeeds on Windows
- [x] `mise run default` (clean → check → setup → build) succeeds on Windows
- [ ] Verify `mise run default` still succeeds on macOS / Linux (no behavioural change expected — `path.isAbsolute()` and `path.relative()` are cross-platform, and the new dependency edge only constrains scheduling)

### CODE REVIEW

**Comment by AttilaMihaly** [comment]
This was based on a confusion caused by accidental commits on main
